### ISSUE TITLE
enhancement: status marker for "Need Info" pending

### ISSUE THREAD

**Issue by hwine** [nchevobbe/bugzilla-timeline#24] opened 2016-08-23 16:36 UTC
Similar to #23 it would be handy to have a visual cue if there is a Need Info pending on the bug. In that case, there may be no action I can take on the bug until the Need Info is answered.

Possible approaches:
- Add notation within hover balloon
- Have a line terminator of something like '?'

**Comment by nchevobbe** [comment] 2016-08-23 17:32
This one might be trickier, since I don't see whether it is returned by the API or not. 
Do you have a bug number currently in needinfo (I don't) so I can check how to retrieve the info ?

**Comment by hwine** [comment] 2016-08-23 23:37
Lots of them :/  [here's one](https://bugzil.la/1238977).  However, I don't see that status on the quick search anywhere. There are reports on everyone's dashboard, but it does seem to be an internal feature. :(

**Comment by nchevobbe** [comment] 2016-08-24 11:52
@hwine that one is not assigned to you, I can't see it in the UI :)
If you have another one, assigned to you, it'll be perfect.
I think we can have the needinfo status through the `flags` property , it would be great. 

@nt1m would you have an idea on how to display such bug ? 
it could be a rectangle terminator with a "?" on it, but I don't find that great. I think you might have better ideas :)

**Comment by hwine** [comment] 2016-08-24 18:04
@nchevobbe sigh - okay [this one](https://bugzil.la/1287612) should be good for next 2 months.

**Comment by nchevobbe** [comment] 2016-08-24 19:31
@hwine that's better :) And I can confirm that we can retrieve the needinfo info in the flags property, so that's great

**Comment by nt1m** [comment] 2016-08-25 06:44
When there's a needinfo, it usually means the bug is blocked on something, so maybe we could mark that with a red round terminator with an exclamation mark ?
We could also color the bug in yellow/black stripes (kinda like a construction site) to insist on that the bug is blocked on something.

**Closed as completed** 2016-09-02 09:08 UTC
